// Generated by CoffeeScript 1.3.3

module.exports = function(store) {
  
  // Query for loggin in
  store.query.expose('people', 'login', function(user) {
    return this
      .where('username').equals(user.username)
      .where('password').equals(user.password);
  });
  
  // Grant global access to the login query
  store.queryAccess('people', 'login', function(user, accept) {
    accept(true);
  });
  
  // Grant access to below if logged in
  var readAccessIfLoggedIn = function() {
      
      var
        session = this.session;
      
      console.log( session );
      
      arguments[ arguments.length - 1 ]( session && session.access !== 'undefined' );
      
    };
  
  store.readPathAccess('people', readAccessIfLoggedIn);
  store.readPathAccess('conf.main.directoryIds', readAccessIfLoggedIn);
  store.writeAccess('*', 'peopleCount', readAccessIfLoggedIn);
  
  /*
  store.writeAccess('*', 'peopleCount', function(arg, accept) {
    accept(true);
  });
  */
  //'peopleCount'
  
};
